# Introduction 

<p style="text-align: justify"> In this jupyter notebook, the main objective is to explore the data from a glass formation dataset initially obtained by the <i> SciGlass Python</i> module, having been pre-processed by Daniel Cassar, and to make the appropriate changes for the use of machine learning methods on the dataset. This dataset initially contains more than 72k examples of glasses, crystals and intermediates compositions, in addition to 319 attributes associated with these materials. There are 317 quantitative attributes of inorganic compounds that may be present in the material, as well as 1 quantitative attribute of a unique code associated with each material (<code>Kod</code>) and 1 qualitative attribute about if the compounds form glass, crystals or intermediates (<code>GF</code>).

### Imported Required Librarie

In [1]:
import pandas as pd

## Exploratory Data Analytics

### Basic Exploratory Data Analytics and Basic Processing 

<p style="text-align: justify"> This subsection shows a brief analysis of the dataset, with a descriptive analysis, exclusion of duplicate examples and a better ordering of the data. Firstly, the file was imported from inside a zip folder and partially displayed to briefly observe it <sup>[1, 2, 3]</sup>.

In [2]:
df = pd.read_csv("../data/raw/GF_data_compound.zip", sep = "\t")
display(df)

,ZnO,Sb2O3,Na2O,MoO3,Bi2O3,TeO2,V2O5,P2O5,B2O3,CaO,...,BiNbO4,Se4I,GeTe4.3,GaTe3,ZnI2,Na2Se,MgS,AsTe3,Kod,GF
0,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21883,Clear glass
1,0.00,0.00,0.0,0.0,0.00,88.55,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,21472,Clear glass
2,0.00,0.00,0.0,0.0,0.00,0.00,25.4,0.00,49.35,25.25,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22665,Glass and crystal
3,0.00,0.00,0.0,0.0,89.70,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,23009,Glass and crystal
4,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24639,Crystal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
72121,0.00,49.96,0.0,0.0,0.00,29.78,0.0,0.00,20.26,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22220,Crystal
72122,0.00,0.00,0.0,0.0,0.00,10.35,0.0,0.00,39.97,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22603,Crystal
72123,20.28,0.00,0.0,0.0,0.00,0.00,0.0,30.02,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,33008,Glass
72124,0.00,0.00,0.0,0.0,48.89,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,22175,Clear glass
72125,0.00,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.00,0.00,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,37056,Crystal


<p style="text-align: justify"> The quantitative attribute of a unique code for each example will be deleted because of the non-relevance in machine learning models. It will also check how many missing and negative elements there are, as well as how many duplicate examples or duplicate attributes there are. In addition, since the attributes are a percentage of the composition of the solid studied, it will be checked how many examples there are where the sum of the attributes doesn't result in 100% <sup>[3, 4, 5, 6]</sup>.

In [3]:
df = df.drop('Kod', axis=1) # drop the code attribute

print('Number of missing values:', df.isnull().sum().sum())
print('Number of negative values:', (((df.drop('GF', axis=1)) < 0).sum().sum()))

print('''Number of duplicated attributes:''', (df.columns.duplicated().sum()))
print('Number of duplicated examples:', df.duplicated().sum())
print('''Number of examples that the sum of attributes doesn't result in 100%:''', (round((df.drop('GF', axis=1)).sum(axis=1), 5) != 100).sum())

Number of missing values: 0
Number of negative values: 474
Number of duplicated attributes: 0
Number of duplicated examples: 1720
Number of examples that the sum of attributes doesn't result in 100%: 0

<p style="text-align: justify"> There are negative elements and duplicate examples, the duplicate examples are deleted. In addition, the number of examples with at least one negative value was checked and descriptive statistics of the dataset were displayed to better understand the negative values <sup>[3, 4, 5, 6]</sup>.

In [4]:
df = df.drop_duplicates(keep=False) # drop_duplicates

print('Number of examples with at least one negative value:', len(df[(df.select_dtypes(include='number') < 0).any(axis=1)]))

pd.set_option('display.max_rows', None)  # show all rows 
pd.set_option('display.max_columns', None) # show all columns

round(df.describe(), 2) # show descriptive statistics of the dataset

Number of examples with at least one negative value: 457

,ZnO,Sb2O3,Na2O,MoO3,Bi2O3,TeO2,V2O5,P2O5,B2O3,CaO,Nb2O5,Ge,Se,Ag,BaO,K2O,SrO,Li2O,La2O3,MgO,ThO2,Al2O3,BeO,ZrO2,TiO2,Ta2O5,WO3,Tl2O,CdO,PbO,In2O3,SnO2,Ga2O3,Cs2O,Rb2O,Y2O3,Sc2O3,SiO2,GeO2,UO2,LaF3,ZrF4,PbF2,Ag2O,MnO,Cu2O,HfO2,AlN,CrO3,Nd2O3,AlF3,Fe2O3,Cr2O3,BaF2,InF3,MgF2,PbCl2,ZnCl2,PbI2,Fe3O4,CeO2,CuO,ThF4,ZnF2,YbF3,YF3,As2O3,Dy2O3,NiO,CoO,LiCl,SrF2,CaF2,Sm2O3,BeF2,KF,VO2,NaF,HgO,MnO2,As2O5,SO3,Na2S,MnF2,KCl,ThCl4,NaCl,BiCl3,CdCl2,PbBr2,CuCl,BaCl2,CsI,BaI2,CuI,ZnBr2,KBr,CdBr2,BaBr2,MgBr2,CaBr2,SrBr2,MnBr2,CoBr2,FeBr2,BiF3,CsF,AgF,AgI,FeO,TmF3,NdF3,TlBr,TlI,GdF3,SnO,SnCl2,Sb,Mn2O3,DyF3,HoF3,ErF3,Sb2O5,Gd2O3,SnF2,Er2O3,Yb2O3,Co2O3,Ni2O3,NiSO4,CdF2,GaF3,UF4,Ca3N2,P3N5,Li3N,FeF3,FeF2,CdI2,KI,PrF3,SmF3,CeF3,EuF3,TbF3,AgBr,AgCl,CrF3,Li2SO4,NaI,SeO3,Pr2O3,S,Ga,As,Cu,EuS,Ga2S3,GeS2,As2Se3,GeTe,I,B,Ni,P,Tl,Bi,BaS,La2S3,Te,Al,Ag2S,GeS,Cl,ZnS,CdS,CdTe,Sb2Se3,GeSe2,Si,Cd,Br,MnS,ZnSe,GeSe3,Tl2S,Sb2S3,As2S3,Cu2Se,SnS,PbS,PbSe,GeSe,Li2S,In,MnCl2,HgTe,Hg,Sn,CaS,SrS,Fe,CdSe,Pb,B2S3,P2S5,SnSe,SnSe2,AsI3,SbI3,BiI3,Fe2S3O12,ZnSO4,K2SO4,AsSe,H2S,SbO2,Ag2Se,HgSe,O,LiI,SiS2,LiBr,Ag4SSe,SnTe,NaPO3,CuPO3,Cu2WO4,Cu3PO4,CuBr,Cu2MoO4,AgPO3,Ag2MoO4,HgI2,As2Te3,BaHPO4,BaP2O6,NbO2F,LiF,BPO4,Sb2Te3,TeI,In2S3,K2S,ZrS2,Ga2Se3,In2Se3,CsBr,Zn,Nd2S3,Eu,BaB2O4,BaGeO3,Al2S3,Na2SO4,PbP2O6,ZnP2O6,Na2B4O7,MgSO4,Bi2S3,AlP3O9,K2NbOF5,Li3PO4,Al2Y2O6,PbTe,CsCl,Li2MoO4,Li2WO4,Na2MoO4,Na2WO4,Ag2Te,Bi2Se3,BaPO3F,ZnTe,HgS,AlPO4,Ho2O3,Li2B4O7,Tl2Se,SrB2O4,Pr6O11,Tb4O7,ErCl3,GdCl3,TmCl3,HoCl3,NdCl3,KPO3,SrSO4,ErPO4,SbP3O9,ScP3O9,HfF4,KHSO4,KBO2,GeTe4,In2Te6,Ga2Te3,KAsO3,Na4As2O7,Co3O4,Er2S3,LiHSO4,NaHSO4,SrCl2,TaO2F,Lu2O3,AsTe,P2Se5,BiNbO4,Se4I,GeTe4.3,GaTe3,ZnI2,Na2Se,MgS,AsTe3
count,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.0,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.0,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.0,69092.00,69092.00
mean,1.98,0.73,2.16,0.62,1.87,8.56,2.31,4.25,10.56,1.80,0.70,1.07,2.79,0.16,2.23,1.43,1.33,1.67,0.71,1.09,0.12,1.54,0.53,0.14,1.57,0.22,0.75,0.54,1.18,2.76,0.09,0.08,1.03,0.27,0.20,0.12,0.07,8.03,4.70,0.02,0.05,0.65,0.27,0.29,0.44,0.02,0.02,0.01,0.02,0.15,0.45,0.49,0.04,0.95,0.11,0.13,0.20,0.15,0.44,0.01,0.06,0.38,0.08,0.31,0.05,0.09,0.01,0.01,0.13,0.15,0.04,0.18,0.20,0.03,0.15,0.07,0.03,0.19,0.01,0.04,0.04,0.02,0.02,0.28,0.15,0.02,0.04,0.0,0.09,0.27,0.05,0.07,0.11,0.01,0.27,0.36,0.27,0.05,0.01,0.01,0.01,0.01,0.0,0.00,0.00,0.09,0.01,0.03,0.72,0.03,0.01,0.03,0.04,0.02,0.02,0.21,0.01,0.20,0.00,0.02,0.01,0.02,0.02,0.02,0.08,0.01,0.01,0.01,0.01,0.01,0.08,0.06,0.08,0.01,0.03,0.03,0.04,0.00,0.08,0.05,0.01,0.00,0.01,0.00,0.02,0.03,0.06,0.03,0.11,0.01,0.00,0.00,1.68,0.05,1.26,0.06,0.01,0.35,1.48,0.67,0.06,0.23,0.03,0.00,0.13,0.17,0.01,0.11,0.01,1.63,0.02,0.31,0.17,0.01,0.03,0.05,0.01,0.25,1.20,0.12,0.03,0.03,0.01,0.03,0.05,0.04,0.25,0.34,0.03,0.03,0.09,0.11,0.18,0.09,0.02,0.01,0.04,0.03,0.04,0.01,0.01,0.00,0.04,0.01,0.04,0.03,0.10,0.07,0.02,0.01,0.01,0.00,0.30,0.17,0.05,0.01,0.01,0.11,0.06,0.04,0.01,0.05,0.03,0.01,0.03,0.47,0.06,0.02,0.04,0.02,0.10,0.07,0.02,0.04,0.07,0.02,0.18,0.05,0.08,0.03,0.03,0.04,0.06,0.02,0.00,0.07,0.03,0.02,0.00,0.00,0.00,0.09,0.10,0.01,0.12,0.07,0.08,0.12,0.06,0.02,0.08,0.05,0.00,0.02,0.03,0.05,0.00,0.01,0.00,0.00,0.01,0.01,0.02,0.00,0.05,0.01,0.01,0.02,0.05,0.03,0.00,0.00,0.01,0.09,0.01,0.01,0.02,0.07,0.03,0.01,0.00,0.01,0.17,0.11,0.01,0.08,0.01,0.00,0.02,0.03,0.02,0.00,0.03,0.04,0.01,0.01,0.01,0.01,0.01,0.02,0.01,0.01,0.00,0.00,0.0,0.01,0.01
std,8.97,6.25,8.92,5.23,8.98,23.45,11.14,13.80,21.86,8.45,5.03,5.54,12.96,2.04,8.93,7.19,7.20,7.64,4.38,6.58,1.55,6.63,4.65,1.69,7.51,2.34,5.63,4.49,7.19,11.28,1.08,1.28,5.92,3.25,2.58,1.60,1.08,19.55,16.08,0.57,0.93,6.07,3.39,3.14,4.39,0.81,0.47,0.54,0.64,2.23,4.10,4.07,1.00,5.88,2.23,2.25,2.94,2.96,4.66,0.46,1.27,3.96,1.81,3.77,1.33,1.77,0.47,0.35,2.30,2.65,1.18,2.52,2.85,0.83,3.22,1.46,0.86,2.75,0.58,1.41,1.33,0.76,0.87,3.57,2.34,0.91,1.14,0.1,1.93,3.75,1.55,1.49,2.03,0.39,3.49,4.41,3.27,1.21,0.62,0.40,0.45,0.67,0.1,0.13,0.09,1.91,0.60,1.26,6.16,0.92,0.65,1.07,1.14,0.87,0.78,3.23,0.62,2.36,0.39,0.86,0.57,0.75,0.62,0.65,2.22,0.48,0.31,0.66,0.57,0.73,1.69,1.43,1.71,0.60,1.09,1.16,1.25,0.25,1.88,1.35,0.33,0.22,0.44,0.33,0.91,1.11,1.57,1.07,2.48,0.54,0.19,0.19,9.94,0.86,6.98,1.09,0.60,3.54,9.47,6.08,1.75,2.76,1.09,0.04,2.15,2.18,0.32,2.22,0.63,9.67,0.60,3.59,2.84,0.73,0.92,1.35,0.45,3.42,8.37,1.76,0.80,0.97,0.35,0.66,1.80,1.25,3.73,4.27,0.99,0.99,1.85,2.09,2.88,2.06,0.59,0.43,1.10,0.64,0.89,0.73,0.81,0.13,0.83,0.39,1.35,1.13,2.16,1.85,0.85,0.63,0.33,0.17,4.33,3.11,1.61,0.88,0.64,1.92,1.47,1.45,0.47,1.63,1.23,0.60,0.87,5.02,1.77,0.70,1.29,0.83,2.15,2.07,0.81,1.27,2.04,1.03,3.35,1.54,1.90,1.29,1.08,1.38,1.29,0.97,0.26,1.35,0.93,0.93,0.12,0.10,0.27,2.14,2.26,0.54,2.58,2.07,2.22,2.62,1.74,0.79,1.81,1.64,0.22,0.91,1.00,1.39,0.46,0.49,0.45,0.53,0.46,0.42,1.06,0.25,1.35,0.52,0.47,1.12,1.62,1.36,0.15,0.18,0.38,2.37,0.38,0.38,1.08,1.91,1.33,0.45,0.38,0.65,3.40,2.34,0.63,2.23,0.58,0.30,1.10,1.32,0.88,0.10,1.41,1.65,0.40,0.51,0.50,0.67,0.56,1.09,0.49,0.98,0.29,0.14,0.3,0.58,0.54
min,-0.20,-1.30,-0.00,-0.00,-0.08,-1.27,0.00,-0.16,-0.00,-0.00,-0.20,-1.00,-0.13,-0.00,-0.30,-0.00,-0.20,-0.47,0.00,-0.46,0.00,-0.00,-0.00,0.00,-0.38,0.00,-0.03,-0.00,-0.00,-0.20,-0.17,-0.00,-1.00,-0.00,-0.00,-0.03,-0.00,-0.20,-0.30,0.00,0.00,0.00,-0.30,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.60,-0.10,0.00,-0.64,-0.00,-0.60,0.00,0.00,-0.60,0.00,0.00,-0.00,0.00,-0.70,0.00,0.00,0.00,0.00,-0.00,-0.00,-0.00,-0.30,-0.20,0.00,0.00,-0.60,0.00,-0.40,-0.00,-0.00,0.00,0.00,0.00,-0.20,0.00,0.00,0.00,0.0,-0.00,0.00,-0.30,0.00,0.00,0.00,0.00,0.00,0.00,-0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,-0.00,0.00,-0.43,0.00,0.00,0.00,0.00,0.00,0.00,-0.20,0.00,-0.27,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.60,0.00,0.00,0.00,-0.00,0.00,-0.13,0.00,0.00,-0.28,-0.00,0.00,0.00,-0.00,0.00,0.00,0.00,-0.00,-0.10,-0.06,0.00,0.00,0.00,-0.20,0.00,0.00,0.00,0.00,0.00,-0.70,-1.19,-0.15,0.00,0.00,0.00,0.00,0.00,0.00,-0.80,-1.33,-0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.11,-0.08,0.00,0.00,0.00,-0.42,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.30,0.00,0.00,-0.60,0.00,-0.80,-0.10,0.00,0.00,0.00,0.00,-0.50,0.00,-0.00,0.00,0.00,0.00,-0.00,0.00,-0.20,0.00,0.00,0.00,0.00,0.00,-0.00,0.00,-0.00,0.00,0.00,0.00,-0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.00,0.00,0.00,-0.30,-0.38,-0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.15,0.00,0.00,0.00,0.00,-0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.00,-0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-0.00,0.0,0.00,0.00
25%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
50%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
75%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
max,93.70,100.00,99.90,94.91,100.00,100.00,99.94,99.76,100.00,90.41,90.36,100.00,101.00,66.70,90.00,94.96,91.93,81.30,90.00,96.44,77.68,100.00,97.35,76.32,91.49,99.98,100.00,90.77,96.90,95.20,50.82,66.83,90.01,75.20,73.15,99.56,39.70,100.39,100.00,39.32,42.55,87.60,99.40,90.60,92.73,49.90,32.38,50.07,47.20,80.20,80.30,81.00,79.61,90.09,80.10,80.26,80.00,100.00,99.98,38.83,50.00,80.30,61.60,81.10,59.10,70.35,44.72,24.00,80.50,82.50,65.40,75.04,82.61,38.60,99.28,69.50,55.04,88.47,66.51,73.98,65.16,47.00,59.88,99.30,66.40,60.04,69.90,14.8,89.70,99.80,99.20,60.20,69.80,30.80,99.79,98.99,66.60,71.40,40.10,25.60,39.80,55.82,10.6,15.40,10.30,65.70,49.89,69.80,99.70,49.56,55.80,79.30,60.30,57.14,50.00,89.70,63.20,89.50,59.20,51.40,40.20,54.10,39.78,35.22,90.10,30.10,25.10,56.21,56.28,80.19,70.50,60.00,65.00,42.40,100.00,79.90,55.20,20.00,70.20,54.79,37.28,27.90,40.10,35.90,90.67,70.80,80.00,59.70,100.00,60.00,30.00,14.93,98.48,34.20,88.29,50.00,59.80,83.77,100.20,99.90,86.10,70.70,69.50,6.30,90.32,59.90,30.01,79.30,50.00,99.70,31.53,81.00,79.20,69.50,61.40,81.73,25.27,92.20,100.01,64.87,49.85,74.40,30.28,33.60,90.17,99.70,100.00,99.55,50.60,54.70,63.10,70.30,80.00,85.00,30.00,40.40,45.60,44.88,60.10,60.90,63.30,11.92,30.53,25.32,100.00,80.00,100.00,100.00,66.70,60.00,41.10,12.42,99.86,99.20,90.90,91.20,40.00,61.90,90.30,66.95,51.70,100.00,75.85,39.50,50.70,100.00,99.90,60.00,75.60,55.50,82.50,99.70,74.10,68.90,99.46,90.40,100.32,60.80,80.70,99.90,61.00,83.40,40.60,85.51,28.40,53.57,50.00,70.04,15.07,10.11,34.40,81.44,90.41,66.50,100.00,100.30,99.70,100.15,99.64,60.40,84.60,82.90,29.70,62.70,57.80,70.00,73.11,67.23,78.60,81.11,54.59,30.29,79.62,21.66,80.83,69.60,35.08,89.11,99.82,100.00,12.71,14.94,40.60,99.60,40.10,40.00,89.90,99.40,99.45,50.54,42.00,50.01,85.62,90.70,50.39,100.43,49.90,25.47,89.66,100.16,80.40,9.36,99.75,99.84,50.50,50.50,26.69,78.50,51.20,71.20,69.20,94.93,39.98,19.40,39.7,70.10,49.80

<p style="text-align: justify"> It's important to understand that negative values are errors, it's impossible to have negative values as a composition. In this sense, the presence of these values is probably human error, these values should most likely be zero. Therefore, the negative numbers will be set to zero and the rows that had negative values will have all the values normalized so that the sum of the attributes results in 100%. After this, it will be checked if there are still negative values and if the sum of the attributes of any row does not result in 100% <sup>[3, 7, 8]</sup>.

In [5]:
categorical_column = df['GF'] # The GF column will be temporarily separated.

df = df.drop('GF', axis=1) # drop "GF" column 

df[df < 0] = 0 # negative numbers are equal to zero

df = df.div(df.sum(axis=1), axis=0) * 100 # normalize the values ​​of each row

print('Number of negative values:', ((df < 0).sum().sum()))

print('''Number of examples that the sum of attributes doesn't result in 100%:''', (round(df.sum(axis=1), 5) != 100).sum())

df = pd.concat([df, categorical_column], axis=1) # add the 'GF' column back to the dataset

Number of negative values: 0
Number of examples that the sum of attributes doesn't result in 100%: 0

<p style="text-align: justify"> Finally, the index will be reset and the size and descriptive statistics of the current dataset will be displayed <sup>[1, 2, 9]</sup>.

In [6]:
df = df.reset_index(drop=True)

print('Dimensionality of the DataFrame:', df.shape) # show the dimensionality of the DataFrame
round(df.describe(), 2)

Dimensionality of the DataFrame: (69092, 318)

,ZnO,Sb2O3,Na2O,MoO3,Bi2O3,TeO2,V2O5,P2O5,B2O3,CaO,Nb2O5,Ge,Se,Ag,BaO,K2O,SrO,Li2O,La2O3,MgO,ThO2,Al2O3,BeO,ZrO2,TiO2,Ta2O5,WO3,Tl2O,CdO,PbO,In2O3,SnO2,Ga2O3,Cs2O,Rb2O,Y2O3,Sc2O3,SiO2,GeO2,UO2,LaF3,ZrF4,PbF2,Ag2O,MnO,Cu2O,HfO2,AlN,CrO3,Nd2O3,AlF3,Fe2O3,Cr2O3,BaF2,InF3,MgF2,PbCl2,ZnCl2,PbI2,Fe3O4,CeO2,CuO,ThF4,ZnF2,YbF3,YF3,As2O3,Dy2O3,NiO,CoO,LiCl,SrF2,CaF2,Sm2O3,BeF2,KF,VO2,NaF,HgO,MnO2,As2O5,SO3,Na2S,MnF2,KCl,ThCl4,NaCl,BiCl3,CdCl2,PbBr2,CuCl,BaCl2,CsI,BaI2,CuI,ZnBr2,KBr,CdBr2,BaBr2,MgBr2,CaBr2,SrBr2,MnBr2,CoBr2,FeBr2,BiF3,CsF,AgF,AgI,FeO,TmF3,NdF3,TlBr,TlI,GdF3,SnO,SnCl2,Sb,Mn2O3,DyF3,HoF3,ErF3,Sb2O5,Gd2O3,SnF2,Er2O3,Yb2O3,Co2O3,Ni2O3,NiSO4,CdF2,GaF3,UF4,Ca3N2,P3N5,Li3N,FeF3,FeF2,CdI2,KI,PrF3,SmF3,CeF3,EuF3,TbF3,AgBr,AgCl,CrF3,Li2SO4,NaI,SeO3,Pr2O3,S,Ga,As,Cu,EuS,Ga2S3,GeS2,As2Se3,GeTe,I,B,Ni,P,Tl,Bi,BaS,La2S3,Te,Al,Ag2S,GeS,Cl,ZnS,CdS,CdTe,Sb2Se3,GeSe2,Si,Cd,Br,MnS,ZnSe,GeSe3,Tl2S,Sb2S3,As2S3,Cu2Se,SnS,PbS,PbSe,GeSe,Li2S,In,MnCl2,HgTe,Hg,Sn,CaS,SrS,Fe,CdSe,Pb,B2S3,P2S5,SnSe,SnSe2,AsI3,SbI3,BiI3,Fe2S3O12,ZnSO4,K2SO4,AsSe,H2S,SbO2,Ag2Se,HgSe,O,LiI,SiS2,LiBr,Ag4SSe,SnTe,NaPO3,CuPO3,Cu2WO4,Cu3PO4,CuBr,Cu2MoO4,AgPO3,Ag2MoO4,HgI2,As2Te3,BaHPO4,BaP2O6,NbO2F,LiF,BPO4,Sb2Te3,TeI,In2S3,K2S,ZrS2,Ga2Se3,In2Se3,CsBr,Zn,Nd2S3,Eu,BaB2O4,BaGeO3,Al2S3,Na2SO4,PbP2O6,ZnP2O6,Na2B4O7,MgSO4,Bi2S3,AlP3O9,K2NbOF5,Li3PO4,Al2Y2O6,PbTe,CsCl,Li2MoO4,Li2WO4,Na2MoO4,Na2WO4,Ag2Te,Bi2Se3,BaPO3F,ZnTe,HgS,AlPO4,Ho2O3,Li2B4O7,Tl2Se,SrB2O4,Pr6O11,Tb4O7,ErCl3,GdCl3,TmCl3,HoCl3,NdCl3,KPO3,SrSO4,ErPO4,SbP3O9,ScP3O9,HfF4,KHSO4,KBO2,GeTe4,In2Te6,Ga2Te3,KAsO3,Na4As2O7,Co3O4,Er2S3,LiHSO4,NaHSO4,SrCl2,TaO2F,Lu2O3,AsTe,P2Se5,BiNbO4,Se4I,GeTe4.3,GaTe3,ZnI2,Na2Se,MgS,AsTe3
count,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.0,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.0,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.00,69092.0,69092.00,69092.00
mean,1.98,0.73,2.16,0.62,1.87,8.56,2.31,4.25,10.56,1.80,0.70,1.07,2.79,0.16,2.23,1.43,1.33,1.67,0.71,1.09,0.12,1.54,0.53,0.14,1.57,0.22,0.75,0.54,1.18,2.76,0.09,0.08,1.03,0.27,0.20,0.12,0.07,8.03,4.70,0.02,0.05,0.65,0.27,0.29,0.44,0.02,0.02,0.01,0.02,0.15,0.45,0.49,0.04,0.95,0.11,0.13,0.20,0.15,0.44,0.01,0.06,0.38,0.08,0.31,0.05,0.09,0.01,0.01,0.13,0.15,0.04,0.18,0.20,0.03,0.15,0.07,0.03,0.19,0.01,0.04,0.04,0.02,0.02,0.28,0.15,0.02,0.04,0.0,0.09,0.27,0.05,0.07,0.11,0.01,0.27,0.36,0.27,0.05,0.01,0.01,0.01,0.01,0.0,0.00,0.00,0.09,0.01,0.03,0.72,0.03,0.01,0.03,0.04,0.02,0.02,0.21,0.01,0.20,0.00,0.02,0.01,0.02,0.02,0.02,0.08,0.01,0.01,0.01,0.01,0.01,0.08,0.06,0.08,0.01,0.03,0.03,0.04,0.00,0.08,0.05,0.01,0.00,0.01,0.00,0.02,0.03,0.06,0.03,0.11,0.01,0.00,0.00,1.68,0.05,1.26,0.06,0.01,0.35,1.48,0.67,0.06,0.23,0.03,0.00,0.13,0.17,0.01,0.11,0.01,1.63,0.02,0.31,0.17,0.01,0.03,0.05,0.01,0.25,1.20,0.12,0.03,0.03,0.01,0.03,0.05,0.04,0.25,0.34,0.03,0.03,0.09,0.11,0.18,0.09,0.02,0.01,0.04,0.03,0.04,0.01,0.01,0.00,0.04,0.01,0.04,0.03,0.10,0.07,0.02,0.01,0.01,0.00,0.30,0.17,0.05,0.01,0.01,0.11,0.06,0.04,0.01,0.05,0.03,0.01,0.03,0.47,0.06,0.02,0.04,0.02,0.10,0.07,0.02,0.04,0.07,0.02,0.18,0.05,0.08,0.03,0.03,0.04,0.06,0.02,0.00,0.07,0.03,0.02,0.00,0.00,0.00,0.09,0.10,0.01,0.12,0.07,0.08,0.12,0.06,0.02,0.08,0.05,0.00,0.02,0.03,0.05,0.00,0.01,0.00,0.00,0.01,0.01,0.02,0.00,0.05,0.01,0.01,0.02,0.05,0.03,0.00,0.00,0.01,0.09,0.01,0.01,0.02,0.07,0.03,0.01,0.00,0.01,0.17,0.11,0.01,0.08,0.01,0.00,0.02,0.03,0.02,0.00,0.03,0.04,0.01,0.01,0.01,0.01,0.01,0.02,0.01,0.01,0.00,0.00,0.0,0.01,0.01
std,8.97,6.25,8.92,5.23,8.98,23.45,11.14,13.80,21.86,8.45,5.03,5.54,12.96,2.04,8.93,7.19,7.20,7.64,4.38,6.58,1.55,6.63,4.65,1.69,7.51,2.34,5.63,4.49,7.19,11.28,1.08,1.28,5.92,3.25,2.58,1.60,1.08,19.55,16.08,0.57,0.93,6.07,3.39,3.14,4.39,0.81,0.47,0.54,0.64,2.23,4.10,4.07,1.00,5.88,2.23,2.25,2.94,2.96,4.66,0.46,1.27,3.96,1.81,3.77,1.33,1.77,0.47,0.35,2.30,2.65,1.18,2.52,2.85,0.83,3.22,1.46,0.86,2.75,0.58,1.41,1.33,0.76,0.87,3.57,2.34,0.91,1.14,0.1,1.93,3.75,1.55,1.49,2.03,0.39,3.49,4.41,3.27,1.21,0.62,0.40,0.45,0.67,0.1,0.13,0.09,1.91,0.60,1.26,6.16,0.92,0.65,1.07,1.14,0.87,0.78,3.23,0.62,2.36,0.39,0.86,0.57,0.75,0.62,0.65,2.22,0.48,0.31,0.66,0.57,0.73,1.69,1.43,1.71,0.60,1.09,1.16,1.25,0.25,1.88,1.35,0.33,0.22,0.44,0.33,0.91,1.11,1.57,1.07,2.48,0.54,0.19,0.19,9.94,0.86,6.98,1.09,0.60,3.54,9.47,6.08,1.75,2.76,1.09,0.04,2.15,2.18,0.32,2.22,0.63,9.67,0.60,3.59,2.84,0.73,0.92,1.35,0.45,3.42,8.37,1.76,0.80,0.97,0.35,0.66,1.80,1.25,3.73,4.27,0.99,0.99,1.85,2.09,2.88,2.06,0.59,0.43,1.10,0.64,0.89,0.73,0.81,0.13,0.83,0.39,1.35,1.13,2.16,1.85,0.85,0.63,0.33,0.17,4.33,3.11,1.61,0.88,0.64,1.92,1.47,1.45,0.47,1.63,1.23,0.60,0.87,5.02,1.77,0.70,1.29,0.83,2.15,2.07,0.81,1.27,2.04,1.03,3.35,1.54,1.90,1.29,1.08,1.38,1.29,0.97,0.26,1.35,0.93,0.93,0.12,0.10,0.27,2.14,2.26,0.54,2.58,2.07,2.22,2.62,1.74,0.79,1.81,1.64,0.22,0.91,1.00,1.39,0.46,0.49,0.45,0.53,0.46,0.42,1.06,0.25,1.35,0.52,0.47,1.12,1.62,1.36,0.15,0.18,0.38,2.37,0.38,0.38,1.08,1.91,1.33,0.45,0.38,0.65,3.40,2.34,0.63,2.23,0.58,0.30,1.10,1.32,0.88,0.10,1.41,1.65,0.40,0.51,0.50,0.67,0.56,1.09,0.49,0.98,0.29,0.14,0.3,0.58,0.54
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
25%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
50%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
75%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.0,0.00,0.00
max,93.70,100.00,99.90,94.91,100.00,100.00,99.94,99.76,100.00,90.41,90.36,99.99,100.00,66.63,90.00,94.96,91.93,81.30,90.00,96.44,77.68,100.00,97.35,76.32,91.49,99.98,100.00,90.77,96.90,95.20,50.82,66.83,90.01,75.20,73.15,99.56,39.70,100.00,100.00,39.32,42.55,87.60,99.40,90.60,92.73,49.90,32.38,50.07,47.20,80.20,80.30,81.00,79.61,90.09,80.10,80.26,80.00,100.00,99.98,38.83,50.00,80.30,61.60,81.10,59.10,70.30,44.72,24.00,80.50,82.50,65.40,75.04,82.61,38.60,99.28,69.50,55.04,88.47,66.51,73.98,65.16,47.00,59.88,99.30,66.40,60.04,69.90,14.8,89.70,99.80,99.20,60.20,69.80,30.80,99.79,98.99,66.60,71.40,40.10,25.60,39.80,55.82,10.6,15.40,10.30,65.70,49.89,69.80,99.70,49.56,55.80,79.30,60.30,57.14,50.00,89.70,63.20,89.50,59.20,51.40,40.20,54.10,39.78,35.22,90.10,30.10,25.10,56.21,56.28,80.19,70.50,60.00,65.00,42.40,100.00,79.90,55.20,20.00,70.20,54.79,37.28,27.90,40.10,35.90,90.67,70.80,80.00,59.70,100.00,60.00,30.00,14.93,98.48,34.20,88.29,50.00,59.80,83.77,100.00,99.90,86.10,70.70,69.50,6.30,90.32,59.90,30.01,79.30,50.00,99.70,31.53,81.00,79.20,69.50,61.40,81.73,25.27,92.20,100.00,64.87,49.85,74.40,30.28,33.60,90.17,99.70,100.00,99.55,50.60,54.70,63.10,70.30,80.00,85.00,30.00,40.40,45.60,44.88,60.10,60.90,63.30,11.92,30.53,25.32,100.00,80.00,100.00,100.00,66.70,60.00,41.10,12.42,99.86,99.20,90.90,91.20,40.00,61.90,89.65,66.95,51.70,100.00,75.85,39.50,50.70,99.90,99.70,60.00,75.60,55.50,82.50,99.70,74.10,68.90,99.46,90.40,100.00,60.80,80.70,99.90,61.00,83.40,40.36,85.51,28.40,53.57,50.00,70.04,15.07,10.11,34.40,81.44,90.41,66.50,100.00,100.00,99.70,100.00,99.64,60.40,84.60,82.90,29.70,62.70,57.80,70.00,73.11,67.23,78.60,81.11,54.59,30.29,79.62,21.66,80.83,69.60,35.08,89.11,99.70,100.00,12.71,14.94,40.60,99.60,40.10,40.00,89.90,99.40,99.45,50.54,42.00,50.01,85.62,90.70,50.39,100.00,49.90,25.47,89.66,100.00,80.40,9.36,99.75,99.84,50.50,50.50,26.69,78.50,51.20,71.20,69.20,94.93,39.98,19.40,39.7,70.10,49.80

## Analysis of Numeric Attributes and <code>GF</code> Labels, and Sorting the Dataset

### Basic Analysis of Numeric Attributes and <code>GF</code> Labels

<p style="text-align: justify"> All the numerical attributes of the dataset were show:

In [7]:
for column in df.columns:
    print(column)

ZnO
Sb2O3
Na2O
MoO3
Bi2O3
TeO2
V2O5
P2O5
B2O3
CaO
Nb2O5
Ge
Se
Ag
BaO
K2O
SrO
Li2O
La2O3
MgO
ThO2
Al2O3
BeO
ZrO2
TiO2
Ta2O5
WO3
Tl2O
CdO
PbO
In2O3
SnO2
Ga2O3
Cs2O
Rb2O
Y2O3
Sc2O3
SiO2
GeO2
UO2
LaF3
ZrF4
PbF2
Ag2O
MnO
Cu2O
HfO2
AlN
CrO3
Nd2O3
AlF3
Fe2O3
Cr2O3
BaF2
InF3
MgF2
PbCl2
ZnCl2
PbI2
Fe3O4
CeO2
CuO
ThF4
ZnF2
YbF3
YF3
As2O3
Dy2O3
NiO
CoO
LiCl
SrF2
CaF2
Sm2O3
BeF2
KF
VO2
NaF
HgO
MnO2
As2O5
SO3
Na2S
MnF2
KCl
ThCl4
NaCl
BiCl3
CdCl2
PbBr2
CuCl
BaCl2
CsI
BaI2
CuI
ZnBr2
KBr
CdBr2
BaBr2
MgBr2
CaBr2
SrBr2
MnBr2
CoBr2
FeBr2
BiF3
CsF
AgF
AgI
FeO
TmF3
NdF3
TlBr
TlI
GdF3
SnO
SnCl2
Sb
Mn2O3
DyF3
HoF3
ErF3
Sb2O5
Gd2O3
SnF2
Er2O3
Yb2O3
Co2O3
Ni2O3
NiSO4
CdF2
GaF3
UF4
Ca3N2
P3N5
Li3N
FeF3
FeF2
CdI2
KI
PrF3
SmF3
CeF3
EuF3
TbF3
AgBr
AgCl
CrF3
Li2SO4
NaI
SeO3
Pr2O3
S
Ga
As
Cu
EuS
Ga2S3
GeS2
As2Se3
GeTe
I
B
Ni
P
Tl
Bi
BaS
La2S3
Te
Al
Ag2S
GeS
Cl
ZnS
CdS
CdTe
Sb2Se3
GeSe2
Si
Cd
Br
MnS
ZnSe
GeSe3
Tl2S
Sb2S3
As2S3
Cu2Se
SnS
PbS
PbSe
GeSe
Li2S
In
MnCl2
HgTe
Hg
Sn
CaS
SrS
Fe
CdSe
Pb
B2S3
P2S5
SnSe
SnSe2
AsI3
SbI3
BiI3
Fe2S3O12
ZnSO4
K2SO4
AsSe
H2S
SbO2
Ag2Se
HgSe
O
LiI
SiS2
LiBr
Ag4SSe
SnTe
NaPO3
CuPO3
Cu2WO4
Cu3PO4
CuBr
Cu2MoO4
AgPO3
Ag2MoO4
HgI2
As2Te3
BaHPO4
BaP2O6
NbO2F
LiF
BPO4
Sb2Te3
TeI
In2S3
K2S
ZrS2
Ga2Se3
In2Se3
CsBr
Zn
Nd2S3
Eu
BaB2O4
BaGeO3
Al2S3
Na2SO4
PbP2O6
ZnP2O6
Na2B4O7
MgSO4
Bi2S3
AlP3O9
K2NbOF5
Li3PO4
Al2Y2O6
PbTe
CsCl
Li2MoO4
Li2WO4
Na2MoO4
Na2WO4
Ag2Te
Bi2Se3
BaPO3F
ZnTe
HgS
AlPO4
Ho2O3
Li2B4O7
Tl2Se
SrB2O4
Pr6O11
Tb4O7
ErCl3
GdCl3
TmCl3
HoCl3
NdCl3
KPO3
SrSO4
ErPO4
SbP3O9
ScP3O9
HfF4
KHSO4
KBO2
GeTe4
In2Te6
Ga2Te3
KAsO3
Na4As2O7
Co3O4
Er2S3
LiHSO4
NaHSO4
SrCl2
TaO2F
Lu2O3
AsTe
P2Se5
BiNbO4
Se4I
GeTe4.3
GaTe3
ZnI2
Na2Se
MgS
AsTe3
GF

<p style="text-align: justify"> All the <code>GF</code> labels and the number of times they are present in the dataset have been displayed. There are 209 labels in total. <sup>[10]</sup>

In [8]:
display(df['GF'].value_counts())

pd.reset_option('display.max_rows')
pd.reset_option('display.max_columns')

GF
Glass                                              25149
Crystal                                            14719
Clear glass                                        10592
Opaque glass                                        2760
Glass and crystal                                   2426
Glass+crystal                                       2013
Imperfect melt                                      1693
Partially opaque glass                              1245
Phase-separated glass                               1046
Glass containing a crystalline part                  719
Glass + crystal                                      701
Unmelted                                             432
Clear glass with crystalline part                    295
Stable glass                                         233
Crystalline                                          217
Opal glass                                           202
Phase separated glass                                181
Phase-separation                                     172
Batch stone                                          171
Homogeneous glass                                    167
Crystal or imperfect melt                            129
Crystallization                                      121
Glass with crystal                                   119
Heterogeneous glass                                  117
Surface crystallization                              114
Fully devitrified glass                              111
Partial divitrification or opal glasses              109
Opaque                                               103
Transparent glass                                     83
Phase-separated                                       75
Incomplete melt                                       72
Contained crystalline material                        68
Partly crystalline                                    65
Partly opal partly homogeneous glass                  65
Trace amounts of crystal in glass                     64
crystal                                               61
Partially devitrified glass                           60
Opal phase-separated glass                            57
Partially crystallization                             57
Glass + crystal or crystal                            56
Partly crystalline partly glassy                      53
Glassy phase                                          52
Crystallized                                          50
Liquid immiscibility                                  49
glass                                                 49
Glass + crystal or phase-separated glass              48
Immiscibility                                         48
Partially or fully devitrified glasses                48
Less than 50% of crystalline phase                    46
Glass+Crystal                                         46
Insufficient melt                                     45
Glass (air-cooled)                                    45
Not melted                                            41
Pure glass                                            38
Contained Crystalline Material                        37
Devitrified                                           34
Rare crystals in the glass                            34
Glass + Crystal                                       34
Partial divitrification or opal glass                 33
Crystall                                              31
Transparent                                           30
Crystallization during working                        29
Immiscible                                            29
Quenched glass                                        29
Grystal                                               27
Crystals + phase-separation                           26
Initial batch                                         24
Devitrification                                       23
Crystal on the surface                                22
Partial crystallization                               22
Air quench glass                                      21
Water quenching glass                                 21
Stable glasses                                        20
Crystal or multi phase                                20
Clear glass (cast)                                    20
Glasses                                               20
Phase separated melt                                  19
Sinter                                                18
Two liquids                                           18
Fast crystallized glass                               18
Volatile                                              17
Undurable glasses                                     17
Glass with single crystals                            17
Not melted at 1400°C                                  17
Glass (15 g of batch)                                 16
crystals                                              16
Glass with the surface crystallization                16
Liquid nitrogen quench glass                          15
Opaque and opal glass                                 15
Cloudy melts                                          15
Single phase glasses                                  14
Ceramic                                               14
Unstable glasses                                      14
Hygroscopic glass                                     14
Incompletely melted                                   14
Phase separated glasses                               13
Glasses exibiting one exotherm in DTA                 13
Crystal with Glass                                    13
Crystals                                              13
Non-glassy phase                                      12
Immiscible or crystalline                             12
Glass+crystall                                        12
Cristal                                               12
Crystal with glass                                    12
Glass with small amount of crystals                   11
Non-transparent                                       11
Phase separated glass or crystal                      11
Class+crystal                                         11
Inhomogeneous glass                                   11
Phase separation glass                                10
Crystal, 1100-1500°C, 10-25 kbar                      10
Opal glass + crystal                                  10
Phase-separeted glass                                 10
Glasses exibiting more than one exotherm in DTA       10
Refractory                                            10
GLass                                                 10
Phase-separarted glass                                 9
Crystalline compounds                                  9
Glear glass                                            9
Partially crystalline                                  9
Partly glass                                           9
Glass (5 g of batch)                                   9
More than 50% of crystalline phase                     9
Glass with crystal or opal glass                       9
Infusible                                              8
Surface crystals                                       8
No glass                                               8
Translucent                                            8
Glass+crystals                                         8
Glass with imperfect melt                              8
glass and crystals                                     8
Glass only by drastic quenching                        8
Glass with crystalline part                            8
Glass with trace of phase-separation                   8
Glass with Crystal                                     8
Immiscible opaque glass                                8
Glass (clay crucible)                                  8
Glass+crystal or phase-separated glass                 7
Clear glass (Quenched)                                 7
Unmelted below 1600°C                                  7
Glass with babls                                       7
Unsatistied glass                                      7
Air cooling glass                                      7
Glass+crystal or crystal                               7
Translucency                                           7
Opaque or transparent glass                            7
Opaque immiscible glass                                7
Crysrtal                                               6
Glassy thin film                                       6
experimental composition                               6
Glass (kyanite crucible)                               6
Class and crystal                                      6
Hygroscopic                                            6
Glass + surface crystals                               6
Immiscibile glass                                      6
Partially crystallized                                 6
Opacity                                                5
Trace amount of crystal in glass                       5
Crystal + phase separation                             5
Bi-phase glasses                                       5
Glass (quenched in water)                              5
Partially crystal                                      5
Non-hygroscopic glass                                  5
Phase-sepatation                                       5
Glass+crysatl                                          5
Clear glass + crystal                                  5
Glass-ceramic                                          5
Crystal + Ag                                           4
Glass containing crystalline part                      4
Glass cooled rapidly                                   4
Liquid-liquid immiscibility                            4
Crysta                                                 4
Glass obtained only at fast cooling                    4
Glass containinng a crystalline part                   4
Glass + cristal                                        4
Liquid phase separation                                4
Phase separated                                        3
Phase separation                                       3
Glass+ceramic                                          3
Crystallized in solution                               3
Part glass                                             3
glass+crystal                                          3
Viscous                                                3
Unstable glass                                         3
Nonfusible at 1450°C                                   3
Glass + traces of Sn                                   3
Immiscible glasses                                     3
Glass, crystallizing on heating                        3
Glass partially reacted with a silica tube             3
Glass cooled slowly                                    3
Trace glass                                            3
Glass obtained by twin-roller quenching                3
Glass + crystals on surface during pouring             2
Glass=crystal                                          2
Crystals on the surface                                2
Immisible opaque glass                                 2
Clear glass containing a crystalline part              2
Partialli opaque glass                                 2
Melt crystallized during pouring                       2
Immiscible melt                                        2
Glass + crystal (formation in water)                   2
Some glass                                             2
Glass with crystal film                                2
Glass containing a crystaliine part                    2
Partially opacue glass                                 1
Glass with bubbles                                     1
Imprefect melt                                         1
Glass containing a cryatalline part                    1
Sintered                                               1
Name: count, dtype: int64

### Sorting the Dataset

<p style="text-align: justify"> Finally, the dataset was sorted based on the <code>GF</code> attribute, using as a criterion the number of times each label is present in the dataset in descending order. <sup>[10]</sup>

In [9]:
df = df.iloc[df.groupby('GF').GF.transform('size').mul(-1).argsort(kind='mergesort',)].reset_index(drop=True)
df = df.reset_index(drop=True)
display(df)

,ZnO,Sb2O3,Na2O,MoO3,Bi2O3,TeO2,V2O5,P2O5,B2O3,CaO,...,P2Se5,BiNbO4,Se4I,GeTe4.3,GaTe3,ZnI2,Na2Se,MgS,AsTe3,GF
0,0.0,0.0,0.00,0.0,0.0,0.00,76.84,4.6,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Glass
1,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Glass
2,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,34.65,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Glass
3,0.0,0.0,16.16,0.0,0.0,83.76,0.00,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Glass
4,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Glass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
69087,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Partially opacue glass
69088,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Glass with bubbles
69089,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Imprefect melt
69090,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Glass containing a cryatalline part
69091,0.0,0.0,0.00,0.0,0.0,0.00,0.00,0.0,0.00,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,Sintered

## Selecting GF Labels

<p style="text-align: justify"> In the previous topic, you can see that there are 209 <code>GF</code> labels about what the composition forms: glass, crystal or an intermediate. To simplify things in a way that is probably more useful for applying machine learning models, the labels will be reduced to just three: crystal (<code>value -1</code>), glass (<code>value 1</code>) and intermediates (<code>value 0</code>). To do this, labels that appear at least 100 times will be analyzed and either classified into one of the three labels mentioned or just deleted. <sup>[11]</sup>

In [10]:
glass = ['Glass','Clear glass', 'Opaque glass', 'Partially opaque glass', 'Phase-separated glass', 'Stable glass', 'Opal glass', 'Phase separated glass', 
        'Phase-separation', 'Homogeneous glass', 'Heterogeneous glass', 'Opaque']
crystal = ['Crystal', 'Crystalline', 'Crystallization']
glass_and_crystal = ['Glass and crystal', 'Glass+crystal', 'Glass containing a crystalline part', 'Glass + crystal', 'Clear glass with crystalline part', 'Glass with crystal']
delete = ['Imperfect melt', 'Unmelted', 'Batch stone', 'Crystal or imperfect melt', 'Surface crystallization', 'Fully devitrified glass', 'Partial divitrification or opal glasses']

labels  = glass + crystal + glass_and_crystal

df = df[df['GF'].isin(labels)] 
df = df.replace(glass, 1).replace(crystal, -1).replace(glass_and_crystal, 0)

Check how many times the labels appear.<sup>[10]</sup>

In [11]:
display(df['GF'].value_counts())

GF
 1    41967
-1    15057
 0     6273
Name: count, dtype: int64

<p style="text-align: justify"> The dimensionality and the descriptive statistics of the current dataset will be displayed <sup>[1, 2, 9]</sup>.

In [12]:
print('Dimensionality of the DataFrame:', df.shape) # show the dimensionality of the DataFrame
round(df.describe(), 2)

Dimensionality of the DataFrame: (63297, 318)

,ZnO,Sb2O3,Na2O,MoO3,Bi2O3,TeO2,V2O5,P2O5,B2O3,CaO,...,P2Se5,BiNbO4,Se4I,GeTe4.3,GaTe3,ZnI2,Na2Se,MgS,AsTe3,GF
count,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00,...,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00,63297.00
mean,1.86,0.71,2.22,0.61,1.85,9.21,2.43,4.14,10.63,1.71,...,0.01,0.02,0.01,0.01,0.00,0.00,0.00,0.01,0.01,0.43
std,8.70,6.17,9.04,5.18,8.92,24.26,11.42,13.69,21.99,8.17,...,0.59,1.04,0.51,1.02,0.30,0.14,0.31,0.60,0.57,0.85
min,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,-1.00
25%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00
50%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00
75%,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,...,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1.00
max,93.70,100.00,99.90,94.91,99.78,100.00,99.94,99.60,100.00,90.41,...,51.20,71.20,69.20,94.93,39.98,19.40,39.70,70.10,49.80,1.00

Finally, the dataset was saved as a <code>.csv</code> file.

In [13]:
df.to_csv("../data/processed/GFdata_compound_processed.csv", index=False)

## References

[1] Cassar, D. R. (2023). Aprendizagem de Máquina, 2.4 - Módulo pandas.

[2] Pereira, D. J. A., & CARVALHO, D. P. L. (2023). Aprendizagem de Máquina, Dados 03 - O Dataset Escolhido.

[3] khedekar, S. (2023, August 26). EDA on Netflix dataset using Pyhton. Kaggle. Retrieved February, 2024, from https://www.kaggle.com/code/swatikhedekar/eda-on-netflix-dataset-using-pyhton.

[4] Inada, I. (2023, August 12).  Counting the number of negative values in Pandas DataFrame. Retrieved February, 2024, from https://www.skytowner.com/explore/counting_the_number_of_negative_values_in_pandas_dataframe.

[5] Hunter, D. (2023b, April 15). Python: Filtering Negative Values in a DataFrame using Python Pandas. CopyProgramming. Retrieved February, 2024, from https://copyprogramming.com/howto/python-pandas-dataframe-filter-negative-values.

[6] note.nkmk.me (2024, January 26). pandas: Find, count, drop duplicates (duplicated, drop_duplicates). Retrieved February, 2024, from https://note.nkmk.me/en/python-pandas-duplicated-drop-duplicates/.

[7] Sharma, P. (2022, September 20) Python - Normalize rows of pandas dataframe by their sums. Retrieved March 2024, from https://www.includehelp.com/python/normalize-rows-of-pandas-dataframe-by-their-sums.aspx.

[8] FavTutor. (2021, November 17). Add Column to DataFrame Pandas (with Examples). Retrieved March 2024, from https://favtutor.com/blogs/pandas-add-column

[9] Saturn Cloud Blog. (2023b, December 12). How to reset index in a Pandas dataframe. Retrieved March 2024, from https://saturncloud.io/blog/how-to-reset-index-in-a-pandas-dataframe/

[10] Hall, P. (2023, May 23). Python: Sorting a Pandas data frame based on value counts in a column: a guide. CopyProgramming. Retrieved February 2024, from https://copyprogramming.com/howto/how-to-sort-a-pandas-data-frame-by-value-counts-of-a-column.

[11] Nelamali, N. (2023, November 29). Pandas filter rows by conditions. Spark by {Examples}. Retrieved March 2024, from https://sparkbyexamples.com/pandas/pandas-filter-rows-by-conditions/.